DROP TABLE IF EXISTS users;

CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    first VARCHAR(200) NOT NULL,
    last VARCHAR (200) NOT NULL,
    email VARCHAR (200) NOT NULL UNIQUE,
    pass VARCHAR (200) NOT NULL,
    pic VARCHAR(300),
    bio VARCHAR(300),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
